# Introduction To Numpy

# Import Libraries

In [3]:
import numpy as np


In [6]:
List=[1,3,2,6,5,7]
print(List)

[1, 3, 2, 6, 5, 7]


In [7]:
array=np.array(List)
print(array)

[1 3 2 6 5 7]


In [11]:
print(len(array))
#print the dimission of arrays
print(array.ndim)

# printing out the shape of the array
print(array.shape)

6
1
(6,)


In [12]:
# reshaping  an array
array2= array.reshape(3,2)
print(array2)

[[1 3]
 [2 6]
 [5 7]]


In [13]:
array2.shape

(3, 2)

In [15]:

#creating arrays with a data type

x=np.array([[1,2], [3,4]], dtype=np.float32)
y = np.array([[5,6],[7,8]], dtype=np.float32)

print(x)


print(y)


[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [16]:
# adding arrays
print(x+y)

[[ 6.  8.]
 [10. 12.]]


In [18]:
#using numpy function
print(np.add(x,y))


[[ 6.  8.]
 [10. 12.]]


In [19]:
#substraction
print(x-y)

[[-4. -4.]
 [-4. -4.]]


In [21]:
#using numpy function

print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]


In [22]:
#dividing array
print(x/y)

[[0.2        0.33333334]
 [0.42857143 0.5       ]]


In [25]:
#diving using numpy function (divide